INSERT INTO `categories` (`id`, `title`, `created_at`, `updated_at`) VALUES
(2, 'Polos', '2025-09-16 12:32:07', '2025-09-16 12:32:07'),
(4, 'Pantalons', '2025-09-16 12:47:39', '2025-09-16 12:47:39'),
(5, 'Tshirts', '2025-09-16 12:47:50', '2025-09-16 12:47:50'),
(6, 'Chaussettes', '2025-09-17 05:47:44', '2025-09-17 05:47:44'),
(8, 'Chemises', '2025-09-17 07:48:42', '2025-09-17 07:48:42');



INSERT INTO `products` (`id`, `title`, `description`, `price`, `stock`, `image`, `category_id`, `created_at`, `updated_at`) VALUES
(1, 'Polo Marron', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam efficitur tortor id mi tempus suscipit. Nulla semper dignissim egestas. Duis imperdiet euismod purus et scelerisque. Sed gravida accumsan diam eget efficitur. Aenean id mi faucibus, cursus augue eu, vehicula lacus. Suspendisse bibendum interdum sapien a tempus. Integer id felis euismod, aliquam massa vel, fermentum felis. Aliquam cursus eu nisi quis vulputate. Aenean ornare arcu ut ligula eleifend, ac efficitur ante elementum. Ut hendrerit vitae tellus sit amet rhoncus. Praesent dictum tempus vestibulum. In efficitur, ipsum sed euismod ultricies, urna tellus dignissim eros, non consectetur sapien nibh vitae risus. In ultrices tellus non ex luctus, non vehicula nibh ullamcorper. Ut placerat eros et sollicitudin tempor. Donec imperdiet dolor vitae arcu sagittis, vel blandit augue viverra.', 20, 100, 'image/BMCZMDNVOsUwShAoslnusyKEFGWRZFlvLrNXZ6z4.jpg', 2, '2025-09-16 13:18:04', '2025-09-16 13:18:04'),
(5, 'Polo Bleu', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam efficitur tortor id mi tempus suscipit. Nulla semper dignissim egestas. Duis imperdiet euismod purus et scelerisque. Sed gravida accumsan diam eget efficitur. Aenean id mi faucibus, cursus augue eu, vehicula lacus. Suspendisse bibendum interdum sapien a tempus. Integer id felis euismod, aliquam massa vel, fermentum felis. Aliquam cursus eu nisi quis vulputate. Aenean ornare arcu ut ligula eleifend, ac efficitur ante elementum. Ut hendrerit vitae tellus sit amet rhoncus. Praesent dictum tempus vestibulum. In efficitur, ipsum sed euismod ultricies, urna tellus dignissim eros, non consectetur sapien nibh vitae risus. In ultrices tellus non ex luctus, non vehicula nibh ullamcorper. Ut placerat eros et sollicitudin tempor. Donec imperdiet dolor vitae arcu sagittis, vel blandit augue viverra.', 21, 50, 'image/2aiI9og1xqERhoMmUOt46u41d82avMz8FVJ65IIh.webp', 2, '2025-09-16 13:27:51', '2025-09-16 13:27:51'),
(6, 'Polo Blanc', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam efficitur tortor id mi tempus suscipit. Nulla semper dignissim egestas. Duis imperdiet euismod purus et scelerisque. Sed gravida accumsan diam eget efficitur. Aenean id mi faucibus, cursus augue eu, vehicula lacus. Suspendisse bibendum interdum sapien a tempus. Integer id felis euismod, aliquam massa vel, fermentum felis. Aliquam cursus eu nisi quis vulputate. Aenean ornare arcu ut ligula eleifend, ac efficitur ante elementum. Ut hendrerit vitae tellus sit amet rhoncus. Praesent dictum tempus vestibulum. In efficitur, ipsum sed euismod ultricies, urna tellus dignissim eros, non consectetur sapien nibh vitae risus. In ultrices tellus non ex luctus, non vehicula nibh ullamcorper. Ut placerat eros et sollicitudin tempor. Donec imperdiet dolor vitae arcu sagittis, vel blandit augue viverra.', 20, 100, 'image/9XXf2yCgwtg6jEvVvoWVnNbxHGqv7lvCgjl4O2Ew.webp', 2, '2025-09-16 13:28:23', '2025-09-16 13:28:23'),
(7, 'Polo Jaune', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam efficitur tortor id mi tempus suscipit. Nulla semper dignissim egestas. Duis imperdiet euismod purus et scelerisque. Sed gravida accumsan diam eget efficitur. Aenean id mi faucibus, cursus augue eu, vehicula lacus. Suspendisse bibendum interdum sapien a tempus. Integer id felis euismod, aliquam massa vel, fermentum felis. Aliquam cursus eu nisi quis vulputate. Aenean ornare arcu ut ligula eleifend, ac efficitur ante elementum. Ut hendrerit vitae tellus sit amet rhoncus. Praesent dictum tempus vestibulum. In efficitur, ipsum sed euismod ultricies, urna tellus dignissim eros, non consectetur sapien nibh vitae risus. In ultrices tellus non ex luctus, non vehicula nibh ullamcorper. Ut placerat eros et sollicitudin tempor. Donec imperdiet dolor vitae arcu sagittis, vel blandit augue viverra.', 19, 40, 'image/v11vzVhZiuhhdBYJKzKtjMZnXJgwoLYUSL76vmnE.webp', 2, '2025-09-16 13:28:46', '2025-09-16 13:28:46'),
(9, 'Tshirt noir', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac lacus dapibus, porta ligula sed, laoreet nunc. Mauris porttitor ipsum eu elit mattis porta eu at odio. Nunc lorem felis, ultricies at odio non, mollis dapibus dolor. In efficitur elementum ipsum, a eleifend sem sodales at. Praesent commodo nulla eu condimentum aliquam. Quisque tincidunt risus et turpis fermentum, id ullamcorper risus pulvinar. Nunc blandit, justo id ornare malesuada, augue elit semper mi, facilisis cursus justo tortor sit amet velit.', 14, 50, 'image/pwcTGaIYMMjlvTqnCGDNwAM4hsZHqOG2cGTGbNHU.webp', 5, '2025-09-17 06:19:20', '2025-09-17 07:41:52'),
(10, 'Tshirt Blanc', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac lacus dapibus, porta ligula sed, laoreet nunc. Mauris porttitor ipsum eu elit mattis porta eu at odio. Nunc lorem felis, ultricies at odio non, mollis dapibus dolor. In efficitur elementum ipsum, a eleifend sem sodales at. Praesent commodo nulla eu condimentum aliquam. Quisque tincidunt risus et turpis fermentum, id ullamcorper risus pulvinar. Nunc blandit, justo id ornare malesuada, augue elit semper mi, facilisis cursus justo tortor sit amet velit.', 11, 50, 'image/MrrB7wDEITML7yd5QDEazZzxugVI2CSgAbhW2xQR.webp', 5, '2025-09-17 07:45:52', '2025-09-17 07:45:52'),
(11, 'Chaussettes Corail', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac lacus dapibus, porta ligula sed, laoreet nunc. Mauris porttitor ipsum eu elit mattis porta eu at odio. Nunc lorem felis, ultricies at odio non, mollis dapibus dolor. In efficitur elementum ipsum, a eleifend sem sodales at. Praesent commodo nulla eu condimentum aliquam. Quisque tincidunt risus et turpis fermentum, id ullamcorper risus pulvinar. Nunc blandit, justo id ornare malesuada, augue elit semper mi, facilisis cursus justo tortor sit amet velit.', 7, 100, 'image/8W51EPH9nvfleAxLULIF60D1X6jyXE7ixYDfRJnL.webp', 6, '2025-09-17 07:46:52', '2025-09-17 07:46:52'),
(12, 'Chaussettes Bleues', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac lacus dapibus, porta ligula sed, laoreet nunc. Mauris porttitor ipsum eu elit mattis porta eu at odio. Nunc lorem felis, ultricies at odio non, mollis dapibus dolor. In efficitur elementum ipsum, a eleifend sem sodales at. Praesent commodo nulla eu condimentum aliquam. Quisque tincidunt risus et turpis fermentum, id ullamcorper risus pulvinar. Nunc blandit, justo id ornare malesuada, augue elit semper mi, facilisis cursus justo tortor sit amet velit.', 7, 100, 'image/9nDOopYbkqHe6W9nhSB92QN6IG51wCLuFeSjksau.webp', 6, '2025-09-17 07:47:22', '2025-09-17 07:47:22'),
(13, 'Pantalon Bleu', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac lacus dapibus, porta ligula sed, laoreet nunc. Mauris porttitor ipsum eu elit mattis porta eu at odio. Nunc lorem felis, ultricies at odio non, mollis dapibus dolor. In efficitur elementum ipsum, a eleifend sem sodales at. Praesent commodo nulla eu condimentum aliquam. Quisque tincidunt risus et turpis fermentum, id ullamcorper risus pulvinar. Nunc blandit, justo id ornare malesuada, augue elit semper mi, facilisis cursus justo tortor sit amet velit.', 40, 20, 'image/yqVsZ8CQFU4OA00SFylalMVTi5ZxZ41z1OeyYilA.webp', 4, '2025-09-17 07:47:58', '2025-09-17 07:47:58'),
(14, 'Pantalon Beige', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac lacus dapibus, porta ligula sed, laoreet nunc. Mauris porttitor ipsum eu elit mattis porta eu at odio. Nunc lorem felis, ultricies at odio non, mollis dapibus dolor. In efficitur elementum ipsum, a eleifend sem sodales at. Praesent commodo nulla eu condimentum aliquam. Quisque tincidunt risus et turpis fermentum, id ullamcorper risus pulvinar. Nunc blandit, justo id ornare malesuada, augue elit semper mi, facilisis cursus justo tortor sit amet velit.', 35, 40, 'image/62JW4L3he40XBUXd8MB55XjnzxyCcjJsS3aCSmNA.webp', 4, '2025-09-17 07:48:27', '2025-09-17 07:48:27'),
(15, 'Chemise Blanche', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent ac lacus dapibus, porta ligula sed, laoreet nunc. Mauris porttitor ipsum eu elit mattis porta eu at odio. Nunc lorem felis, ultricies at odio non, mollis dapibus dolor. In efficitur elementum ipsum, a eleifend sem sodales at. Praesent commodo nulla eu condimentum aliquam. Quisque tincidunt risus et turpis fermentum, id ullamcorper risus pulvinar. Nunc blandit, justo id ornare malesuada, augue elit semper mi, facilisis cursus justo tortor sit amet velit.', 25, 100, 'image/uo2jdOcVnQLMXWEzs9QOsofbNZyTW72oBmmoANLF.webp', 8, '2025-09-17 07:49:14', '2025-09-17 07:49:14');